### ISSUE TITLE
problems with postea

### ISSUE THREAD

**Issue by creatorofspark** [FalsePattern/ChunkAPI#10]
Hi! i know i might be wrong about it, but i think chunkapi has some problems with GTNH's postea mod, my game crashed when i was about to create world
[fml-client-latest.log](https://github.com/user-attachments/files/18061619/fml-client-latest.log)

**Comment by FalsePattern** [comment]
I made a PR to postea: https://github.com/GTNewHorizons/Postea/pull/8

**Comment by creatorofspark** [comment]
great!

**Comment by FalsePattern** [comment]
You can use this temporary release until they merge the fix:
https://github.com/FalsePattern/Postea/releases/tag/1.0.13-chunkapi-fixed

**Comment by creatorofspark** [comment]
[fml-client-latest.log](https://github.com/user-attachments/files/18095182/fml-client-latest.log)

**Comment by FalsePattern** [comment]
Update ChunkAPI to 0.6.0 and EndlessIDs to 1.6.0

**Comment by creatorofspark** [comment]
it works

**Comment by FalsePattern** [comment]
Postea 1.1.0 has support for chunkapi/endlessids
