### ISSUE TITLE
Client crash during SMP connection

### ISSUE THREAD

**Issue by jacobrham** [FalsePattern/ChunkAPI#2]
ChunkAPI seems to cause a crash when connecting to a multiplayer server also with ChunkAPI. I've tested a very minimal installation with only whats necessary to boot the mod (FalsePatternLib, GasStation, Forge, BetterCrashes) and observed that connecting without Chunkapi is fine, but adding it to the client and server causes a crash. Loading a singleplayer world works fine.

Steps to reproduce:
Spin up client and server instances with the latest versions of Forge, FalsePatternLib, GasStation, and ChunkAPI for 1.7.10.
Connect to the server instance from the client. 
The client should crash and produce a crash report like the one attached.

Expected behavour:
ChunkAPI should operate in singleplayer and multiplayer contexts.

I've attached a client crash report of the client as well as logs for the client and server.
[crash-2023-04-15_10.13.40-client.txt](https://github.com/FalsePattern/ChunkAPI/files/11239748/crash-2023-04-15_10.13.40-client.txt)
[fml-client-latest.log](https://github.com/FalsePattern/ChunkAPI/files/11239804/fml-client-latest.log)
[fml-server-latest.log](https://github.com/FalsePattern/ChunkAPI/files/11239811/fml-server-latest.log)

**Comment by FalsePattern** [comment]
Fixed in 0.1.2
