### ISSUE TITLE
Confusion about the additional permissions in the license

### ISSUE THREAD

**Issue by benjamin-kirkbride** [FalsePattern/ChunkAPI#8]
At the top of the license, it says

> This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

But what comes after is significantly modified from "the terms of the GNU Affero General Public License as published by the Free Software Foundation".

**Comment by benjamin-kirkbride** [comment]
> You may link This Mod against the proprietary code of The Game, as well as
distribute binary builds of it as part of a Modpack without the AGPL
restrictions spreading to any other files in that Modpack.

What does "without the AGPL restrictions" mean? That is not a term that appears anywhere in the license.

**Comment by FalsePattern** [comment]
> At the top of the license, it says
> 
> > This program is free software: you can redistribute it and/or modify
> > it under the terms of the GNU Affero General Public License as published by
> > the Free Software Foundation, either version 3 of the License, or
> > (at your option) any later version.
> 
> But what comes after is significantly modified from "the terms of the GNU Affero General Public License as published by the Free Software Foundation".

It is not a modified version of the AGPL license, those are additional permissions as per Section 7 of the AGPL:

```
 "Additional permissions" are terms that supplement the terms of this
License by making exceptions from one or more of its conditions.
Additional permissions that are applicable to the entire Program shall
be treated as though they were included in this License, to the extent
that they are valid under applicable law.  If additional permissions
apply only to part of the Program, that part may be used separately
under those permissions, but the entire Program remains governed by
this License without regard to the additional permissions.
```

**Comment by FalsePattern** [comment]
> > You may link This Mod against the proprietary code of The Game, as well as
> > distribute binary builds of it as part of a Modpack without the AGPL
> > restrictions spreading to any other files in that Modpack.
> 
> What does "without the AGPL restrictions" mean? That is not a term that appears anywhere in the license.

The "AGPL restrictions" means the restrictions given in AGPL against linking proprietary code, or code that depends on my code having to be licensed under the GPL or AGPL too.

**Comment by FalsePattern** [comment]
The additional permissions given in the license are quite straightforward in my opionion, it allows you to link my AGPL-licensed code against Mojang's proprietary codebase, given some simple terms. You're free to remove these additional terms (or, they get automatically removed if you breach section C of the additional permissions)

This is also fully within the AGPL additional permissions framework, as per section 7:
```
 When you convey a copy of a covered work, you may at your option
remove any additional permissions from that copy, or from any part of
it.  (Additional permissions may be written to require their own
removal in certain cases when you modify the work.)
```
