### ISSUE TITLE
not compatible with voxelmap

### ISSUE THREAD

**Issue by huihiuhuai** [FalsePattern/ChunkAPI#9]

**Comment by huihiuhuai** [comment]
![image](https://github.com/user-attachments/assets/56a397ab-89ed-454a-9ff0-e9392d17a1eb)

**Comment by FalsePattern** [comment]
Doesn't happen for me with only falsepatternlib + chunkapi + liteloader + voxelmap. Please send your full modlist, and try removing other mods one by one until it stops happening.

**Comment by huihiuhuai** [comment]
RPLE is incompatible

**Comment by huihiuhuai** [comment]
modlist is rple and dependencies and voxelmap

**Comment by FalsePattern** [comment]
Then please open an issue on the RPLE repository.
